project:
  type: website
  preview: 
    port: 4200

website:
  title: "Veri Defteri"
  favicon: img/veridefteri_ikon.png
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/veridefteri
format:
  html:
    theme: flatly
    css: styles.css



